# Generated by Django 3.2.4 on 2021-07-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poke_type', models.CharField(max_length=100)),
                ('strongest_attack', models.CharField(max_length=100)),
                ('date_caught', models.CharField(max_length=100)),
            ],
        ),
    ]
