# Generated by Django 3.2.4 on 2021-07-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_pokemon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='team',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
