# Generated by Django 3.2.4 on 2021-07-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='boost',
            field=models.IntegerField(default=2, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='X-Attack', editable=False, max_length=100),
        ),
    ]
