# Generated by Django 3.2.4 on 2021-07-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210707_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='item',
        ),
    ]
