# Generated by Django 3.2.4 on 2021-07-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_pokemon_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='boost',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='X-Attack', max_length=100),
        ),
    ]
