# Generated by Django 3.2.4 on 2021-07-07 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210707_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.item'),
            preserve_default=False,
        ),
    ]
