# Generated by Django 3.2.4 on 2021-07-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='attacks',
            field=models.ManyToManyField(to='main_app.Attack'),
        ),
    ]
