# Generated by Django 3.2.4 on 2021-07-08 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_pokemon_attacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='strongest_attack',
        ),
    ]
